print("I will be 100 years old in the year 2080")
name = input("what is your name: ")
age = str(input("how old are you: "))
year = str((2018 - age)+100)
print(name + " will be" + age + "years old in 2090" + year)